### ISSUE TITLE
Method to Automatically Reload Containers If Configuration Changes

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#52]
For example if an administrator changes the ssl_key or ssl_cert, we need a method that involving a sidecar container to restart the impacted container. In this case, oxAuth and oxTrust would download the new keys and restart automatically.

**Comment by iromli** [comment]
Due to how we design the container, we can periodically check the updates from inside a container. But then restarting the main process inside container will kill the container, not restarting it. This is more into scheduler things. Also we have docs on how to update cert and key now.

Closing this issue.
